### PR TITLE
Dbtools

### LINKED ISSUE #17: Dummy User Data Generation
There needs to be a tool that developers can use to generate dummy data for the Firebase database.

It should be able to generate user data that matches all specifications in the App Data document.

Also, to prevent data cluttering, it should be able to remove all data it generated from the database.

### PR DESCRIPTION
**Pull request by asclines**
Closes #17 
Allows for person creation, generates random data AND allows overriding of generated data to aide developers in the building and testing of this app.
Also logs the people it creates to make for easier removal when you are done with these people.

### CODE REVIEW

**Comment by asclines** [comment]
@NilsG-S Thanks for catching that, I forgot to put the usage output in the documentation. I went ahead and added that.  Idk if that was the only thing you were going to do or not with changing the documentation, but if it wasn't feel free to push any additional changes to the documentation as you see fit.

**Comment by asclines** [comment]
@NilsG-S You are correct about the email mismatch. It's from the 3 static users I have in there. I manually edited their emails from the Firebase web console after creation. If that becomes an issue I can fix it.

**Comment by NilsG-S** [comment]
I might go ahead and add a few other things, since it's alright

**Comment by NilsG-S** [comment]
@asclines What do you think?

**Comment by asclines** [comment]
@NilsG-S Nice! Much easier to understand than what I wrote

**Comment by NilsG-S** [comment]
Huh. I can't actually tell how it detected that yours was a list and not mine, there's no discernible difference on my editor. Anyway, should we merge it?

**Pull request merged**
